"""Regenerate asc_grid_stage3.json (bike + car_passenger travel-time beta sweep).

Each grid cell pairs a beta with an ASC that compensates the mean-utility shift,
so the mode's share does not collapse and distance_mae_km stays interpretable.

Run this instead of hand-editing the json: the per-run bike/car_passenger alphas
are DERIVED from ALPHA below, so changing an alpha by hand in the json would
silently break the compensation.

After stage 2 finishes, update ALPHA (and the medians, if the LOS moved much)
and re-run:  python gen_stage3_grid.py
"""
import json
from pathlib import Path

OUT = Path(__file__).with_name("asc_grid_stage3.json")

# Best current alpha estimate. Stage-1 ln(target/sim) update point - REFRESH THIS
# from the stage-2 winner before launching stage 3.
ALPHA = {
    "car.alpha_u": 0.0,
    "walk.alpha_u": -0.46,
    "pt.alpha_u": -0.386,
    "bike.alpha_u": -1.63,
    "bavariaCarPassenger.alpha_u": -2.31,
    "bavariaDrt.alpha_u": -0.5969,
}

# Beta values the swept modes currently sit at (the compensation is relative to these).
BIKE_BETA_BASE = -0.0845
CP_BETA_BASE = -0.0761

# Median trip time per mode, from the stage-1 best run. Median on purpose - see
# the note in the generated _comment.
BIKE_MEDIAN_MIN = 14.3
CP_MEDIAN_MIN = 18.0

BIKE_BETAS = [-0.0845, -0.1014, -0.1183, -0.1352, -0.1690]   # 1.0x .. 2.0x
CP_BETAS = [-0.0761, -0.1000, -0.1300, -0.1600]              # 1.0x, old value, 1.7x, 2.1x


def build_runs():
    runs = []
    for bb in BIKE_BETAS:
        for cpb in CP_BETAS:
            d_bike_alpha = -(bb - BIKE_BETA_BASE) * BIKE_MEDIAN_MIN
            d_cp_alpha = -(cpb - CP_BETA_BASE) * CP_MEDIAN_MIN

            runs.append({
                "name": f"bb{bb:.4f}_cpb{cpb:.4f}",
                "parameters": {
                    "bike.betaTravelTime_u_min": round(bb, 4),
                    "bavariaCarPassenger.betaInVehicleTravelTime_u_min": round(cpb, 4),
                    "bike.alpha_u": round(ALPHA["bike.alpha_u"] + d_bike_alpha, 4),
                    "bavariaCarPassenger.alpha_u": round(ALPHA["bavariaCarPassenger.alpha_u"] + d_cp_alpha, 4),
                },
            })
    return runs


def main():
    runs = build_runs()

    spec = {
        "_comment": [
            f"Stage-3 sweep: bike + car_passenger travel-time betas. {len(runs)} runs.",
            "GENERATED by gen_stage3_grid.py - regenerate, do not hand-edit.",
            "WHY betas and not ASCs: stage 1 showed ASCs barely move trip lengths - a",
            "0.2-util bike ASC range shifted the bike median by 0.04 km. Lengths are",
            "governed by the time betas, shares by the ASCs.",
            "Targets (stage-1 best run, median): bike 3.58 km vs 2 km MiD (+79%),",
            "car_passenger 9.83 km vs 6 km (+64%). Both need MORE negative time betas.",
            "car_passenger also starts from a suspicious place: the new survey WEAKENED",
            "its beta from -0.10 to -0.0761, so -0.1000 is included to test whether that",
            "weakening caused the length regression.",
            "",
            "EVERY cell pairs its beta with a compensated ASC:",
            "  dAlpha = -(beta_new - beta_base) * median_trip_time",
            f"  bike:          base {BIKE_BETA_BASE}, median {BIKE_MEDIAN_MIN} min",
            f"  car_passenger: base {CP_BETA_BASE}, median {CP_MEDIAN_MIN} min",
            "This pivots each mode's utility around its typical trip: long trips get",
            "much worse while the median trip's utility stays put, so the mode's share",
            "does not collapse and distance_mae_km stays interpretable.",
            "Median, not mean, on purpose: the means (bike 31.4 min, cp 26.4 min) are",
            "inflated by the very tail we want to remove, so mean-based compensation",
            "would over-correct.",
            "",
            "Residual share drift IS expected - the compensation is first-order only,",
            "and the fixed point moves as the tail shrinks. Judge length fit by",
            "distance_mae_km and share fit by share_mae_pp SEPARATELY; a final cheap",
            "ASC pass (ln(target/sim), 1-2 single runs) cleans up the shares afterwards.",
            "",
            "The alphas here build on the stage-1 update point. If stage 2 produces",
            "better alphas, update ALPHA in gen_stage3_grid.py and regenerate.",
            "Cell bb-0.0845_cpb-0.0761 is the unchanged-beta anchor for this scenario.",
        ],
        "base": dict(ALPHA),
        "extra_args": ["--use-vdf", "true"],
        "runs": runs,
    }

    OUT.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} with {len(runs)} runs")

    print(f"\n{'run':26} {'bike_beta':>10} {'bike_alpha':>11} {'cp_beta':>9} {'cp_alpha':>9}")
    for r in runs:
        p = r["parameters"]
        print(f"{r['name']:26} {p['bike.betaTravelTime_u_min']:>10} {p['bike.alpha_u']:>11} "
              f"{p['bavariaCarPassenger.betaInVehicleTravelTime_u_min']:>9} "
              f"{p['bavariaCarPassenger.alpha_u']:>9}")


if __name__ == "__main__":
    main()
