"""Regenerate asc_grid_stage4.json - fourth and intended final round.

Stage 3 reached share_mae 1.251 pp / dist_mae 0.937 km, and the additivity
assumption it rested on held: all five mvv shares were predicted on target and
three of them landed within 0.3 pp.

What is left:
  - the ASC solve from the stage-3 gradient (small, all four positive)
  - bicycle length regressed to +1.12 km as a composition effect of its falling
    share; its beta has never been adopted (the -0.12 probe dates from stage 1)

Deliberately NOT pursued:
  - pt beta: the umland is already overshot at -0.06 (mvv +0.94, munich +2.39,
    umland -2.79). A single global beta cannot close munich without pushing the
    umland further, so this stops here.
  - car length (-1.17 km): composition-dependent and car's effective beta is
    already only -0.0397 (10.9 EUR/h). Wrong instrument.

Note on where this is heading: MiD share targets are rounded to whole percent
and the distances to whole km, so a share_mae near 1 pp is approaching the
resolution of the reference data itself. Tuning much past that fits noise.

Run: python gen_stage4_grid.py
"""
import json
from pathlib import Path

import numpy as np

OUT = Path(__file__).with_name("asc_grid_stage4.json")

MODES = ["walk", "bicycle", "car_passenger", "car", "pt"]
SWEPT = ["walk.alpha_u", "bike.alpha_u", "bavariaCarPassenger.alpha_u", "pt.alpha_u"]

# Stage-3 centre, its realised mvv shares, and the gradient measured there.
S3_CENTRE = {
    "walk.alpha_u": -0.1209,
    "bike.alpha_u": -1.2644,
    "bavariaCarPassenger.alpha_u": -1.5841,
    "pt.alpha_u": 0.6819,
}
S3_SHARES = np.array([20.82, 15.18, 10.86, 35.41, 17.73])
TARGET = np.array([21.0, 15.0, 12.0, 34.0, 18.0])

J = np.array([
    [9.41, -5.27, -1.55, -0.59],
    [-5.32, 11.48, -1.91, -2.77],
    [-1.47, -1.93, 6.69, -0.67],
    [-2.10, -1.46, -2.42, -1.70],
    [-0.52, -2.82, -0.81, 5.74],
])

# Betas carried over from stage 3.
BETAS = {
    "bavariaCarPassenger.betaInVehicleTravelTime_u_min": -0.13,
    "pt.betaInVehicleTime_u_min": -0.06,
}

BIKE_BETA_BASE = -0.0995

# Share effect of bike beta -0.0995 -> -0.12, measured in stage 1 (mvv, pp).
# That was at 35.26% bicycle share against 15.18% now, so it is scaled by the
# share ratio for the compensated variant. Crude, which is exactly why the
# uncompensated probes are in this round too - they measure it properly.
BIKE_EFFECT_S1 = np.array([1.31, -5.17, 0.77, 1.27, 1.81])
BIKE_SCALE = 15.18 / 35.26


def solve(shares_before):
    delta, *_ = np.linalg.lstsq(J, TARGET - shares_before, rcond=None)
    return delta


CENTRE_DELTA = solve(S3_SHARES)
CENTRE = {k: round(S3_CENTRE[k] + d, 4) for k, d in zip(SWEPT, CENTRE_DELTA)}

STEP = 0.2


def build_runs():
    runs = [{"name": "C_centre", "parameters": {**CENTRE, **BETAS}}]

    for key in SWEPT:
        short = {"walk.alpha_u": "walk", "bike.alpha_u": "bike",
                 "bavariaCarPassenger.alpha_u": "cp", "pt.alpha_u": "pt"}[key]
        for sign in ("+", "-"):
            p = {**CENTRE, **BETAS}
            p[key] = round(CENTRE[key] + (STEP if sign == "+" else -STEP), 4)
            runs.append({"name": f"A_{short}{sign}{STEP}", "parameters": p})

    # Uncompensated: these measure the bike beta's share effect cleanly at this
    # centre. Judge them on bicycle length, not on share_mae.
    for b in [-0.11, -0.12]:
        p = {**CENTRE, **BETAS, "bike.betaTravelTime_u_min": b}
        runs.append({"name": f"B_bike{b}", "parameters": p})

    # Compensated best guess. The centre is solved to sit on TARGET, so applying
    # the bike beta moves it to TARGET + effect, and the ASCs have to undo that.
    # Same beta step as the stage-1 measurement (-0.0995 -> -0.12), so only the
    # share-ratio scaling applies.
    effect = BIKE_EFFECT_S1 * BIKE_SCALE
    delta = solve(TARGET + effect)
    p = {**BETAS, "bike.betaTravelTime_u_min": -0.12}
    for key, d in zip(SWEPT, delta):
        p[key] = round(CENTRE[key] + d, 4)
    runs.append({"name": "B_bike-0.12c", "parameters": p})

    return runs


def main():
    runs = build_runs()

    spec = {
        "_comment": [
            f"Stage-4 on the Table-2 specification. {len(runs)} runs. Intended as",
            "the final round.",
            "GENERATED by gen_stage4_grid.py - regenerate, do not hand-edit.",
            "",
            "Stage 3: share_mae 1.251 pp, dist_mae 0.937 km (from 8.129/3.329 at",
            "stage 1). Its additivity assumption held - all five mvv shares were",
            "predicted on target, three landed within 0.3 pp.",
            "",
            "C_centre  the ASC solve from the stage-3 gradient. Small, all four",
            "          positive, because car is the only mode above target (+1.41).",
            "          Cross-check: stage 3's A_cp+0.25 sat almost exactly on the",
            "          solved cp value and did improve share_mae to 1.206.",
            "A_*       axes at +-0.2 for a final gradient. It has nearly settled",
            "          (largest change from stage 2 to 3 was 1.5 pp/u), so this is",
            "          confirmation rather than discovery.",
            "B_bike*   bicycle length regressed from +0.40 to +1.12 km as its share",
            "          fell - a composition effect. Its beta was probed once in",
            "          stage 1 (-0.12) but never adopted. -0.11 and -0.12 are",
            "          UNCOMPENSATED on purpose: they measure the share effect",
            "          cleanly at this centre, so judge them on bicycle length.",
            "B_bike-0.12c  the same beta with an ASC compensation estimated from",
            "          the stage-1 effect scaled by the share ratio (35.3% -> 15.2%).",
            "          That scaling is crude; if this run lands, the calibration is",
            "          finished, and if it does not, the two probes give the exact",
            "          compensation to apply analytically.",
            "",
            "NOT pursued:",
            "  pt beta stops at -0.06. The zonal split is already inverted - mvv",
            "  +0.94, munich +2.39, umland -2.79 km - so a global beta cannot close",
            "  munich without driving the umland further negative.",
            "  car length (-1.17 km) is composition-dependent and car's effective",
            "  beta is already -0.0397 (10.9 EUR/h); weakening it further to buy",
            "  distance would be the wrong instrument.",
            "",
            "STOPPING CRITERION: MiD share targets are rounded to whole percent and",
            "distances to whole km, and per-cell sampling error is plausibly 1-2 pp.",
            "At share_mae ~1 pp further tuning fits the reference data's noise.",
        ],
        "base": {"car.alpha_u": 0.0, **CENTRE, **BETAS},
        "extra_args": ["--use-vdf", "true"],
        "runs": runs,
    }

    OUT.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} with {len(runs)} runs\n")
    print(f"stage-3 centre -> stage-4 centre:")
    for k in SWEPT:
        print(f"  {k:32} {S3_CENTRE[k]:+.4f} -> {CENTRE[k]:+.4f}")
    print()
    print(f"{'run':16} {'walk':>9} {'bike':>9} {'cp':>9} {'pt':>9}  bike_beta")
    for r in runs:
        p = r["parameters"]
        bb = p.get("bike.betaTravelTime_u_min", "")
        print(f"{r['name']:16} {p['walk.alpha_u']:>9} {p['bike.alpha_u']:>9} "
              f"{p['bavariaCarPassenger.alpha_u']:>9} {p['pt.alpha_u']:>9}  {bb}")


if __name__ == "__main__":
    main()
