"""Regenerate asc_grid_stage2.json - second round on the Table-2 specification.

Stage 1 was a screening round. Its centre (Table 2 exactly as estimated) came
out at share_mae 8.13 pp, dominated by bicycle at 35.3% against a 15% target.
From the measured gradient (mvv, pp per utility)

               walk    bike      cp      pt
    walk      10.98   -8.86   -0.08   -0.02
    bicycle   -9.19   19.61   -2.29   -3.50
    cp         0.08   -2.08    6.09   -0.51
    car       -1.96   -5.06   -3.12   -1.17
    pt         0.09   -3.61   -0.60    5.20

a least-squares solve gives the ASC update in SOLVED_DELTA below. Note that the
plain per-mode ln(target/sim) would have moved walk the WRONG WAY (+0.11 instead
of -0.97): walk is below target, but bicycle has to drop by 1.44, which lifts
walk by ~12.8 pp through the cross effect, so walk has to come down as well.

That solve is an extrapolation - the gradient was measured at +-0.4 u, the update
asks for -0.97 and -1.44 - so this round does three things at once:

  R_* / C_centre  walk the solution ray at 0.7x / 1.0x / 1.3x of the solved step.
                  This is the direct linearity test along the direction that
                  matters, and it brackets an overshoot in either direction.
  A_*             axes at +-0.3 around the new centre, to re-measure the gradient
                  locally. Stage 1's gradient is only valid near Table 2.
  B_*             beta probes for the two modes whose trips are far too long.

Run: python gen_stage2_grid.py
"""
import json
from pathlib import Path

OUT = Path(__file__).with_name("asc_grid_stage2.json")

# Stage-1 centre (Table 2 as estimated).
STAGE1_CENTRE = {
    "walk.alpha_u": 0.8438,
    "bike.alpha_u": 0.4624,
    "bavariaCarPassenger.alpha_u": -2.0608,
    "pt.alpha_u": -0.1226,
}

# Least-squares solution of J @ delta = (target - simulated) on the mvv shares.
SOLVED_DELTA = {
    "walk.alpha_u": -0.9723,
    "bike.alpha_u": -1.4443,
    "bavariaCarPassenger.alpha_u": 0.0164,
    "pt.alpha_u": 0.2381,
}

RAY_FRACTIONS = [0.7, 1.3]   # 1.0 is the centre itself
STEP = 0.3                   # axis step around the new centre

# car_passenger medians were 15.26 km against a 6 km target at the stage-1 centre;
# beta -0.1000 brought that to 6.36 km, i.e. roughly -80 km per unit of beta.
# Closing the rest needs about -0.08 more, hence this ladder.
CP_BETAS = [-0.13, -0.16, -0.19]

# pt responded far more weakly: -0.0253 of beta bought only -0.59 km of the
# 5.47 km error. Two moderate probes are enough to confirm whether the time beta
# is the right lever here at all - see the note in the generated _comment.
PT_BETAS = [-0.06, -0.09]


def ray(fraction):
    return {k: round(STAGE1_CENTRE[k] + fraction * SOLVED_DELTA[k], 4) for k in STAGE1_CENTRE}


CENTRE = ray(1.0)


def build_runs():
    runs = [{"name": "C_centre", "parameters": dict(CENTRE)}]

    for f in RAY_FRACTIONS:
        runs.append({"name": f"R_ray{f}", "parameters": ray(f)})

    for key in STAGE1_CENTRE:
        short = {"walk.alpha_u": "walk", "bike.alpha_u": "bike",
                 "bavariaCarPassenger.alpha_u": "cp", "pt.alpha_u": "pt"}[key]
        for sign in ("+", "-"):
            delta = STEP if sign == "+" else -STEP
            params = dict(CENTRE)
            params[key] = round(CENTRE[key] + delta, 4)
            runs.append({"name": f"A_{short}{sign}{STEP}", "parameters": params})

    for b in CP_BETAS:
        params = dict(CENTRE)
        params["bavariaCarPassenger.betaInVehicleTravelTime_u_min"] = b
        runs.append({"name": f"B_cp{b}", "parameters": params})

    for b in PT_BETAS:
        params = dict(CENTRE)
        params["pt.betaInVehicleTime_u_min"] = b
        runs.append({"name": f"B_pt{b}", "parameters": params})

    return runs


def main():
    runs = build_runs()

    spec = {
        "_comment": [
            f"Stage-2 on the Table-2 specification. {len(runs)} runs.",
            "GENERATED by gen_stage2_grid.py - regenerate, do not hand-edit.",
            "",
            "Stage-1 centre (Table 2 as estimated) was share_mae 8.13 pp, driven by",
            "bicycle at 35.3% against a 15% target. The new centre is the",
            "least-squares solution of the MEASURED gradient, not of the per-mode",
            "ln(target/sim) formula - that formula would have moved walk the wrong",
            "way, because bicycle's drop lifts walk through a -8.9 pp/u cross effect.",
            "",
            "C_centre / R_*  the solution ray at 1.0x / 0.7x / 1.3x of the solved",
            "                step. The solve extrapolates well past the +-0.4 u the",
            "                gradient was measured over, so linearity along this",
            "                direction is the main thing being tested.",
            "A_*             axes at +-0.3 around the new centre - the stage-1",
            "                gradient is only valid near Table 2 and has to be",
            "                re-measured once we have moved this far.",
            "B_cp*           car_passenger is the worst length error: 15.26 km",
            "                against 6 km at the stage-1 centre, and beta -0.1000",
            "                only got it to 6.36 km. The ladder continues from there.",
            "B_pt*           pt trips are 13.47 km against 8 km, but the beta barely",
            "                moves them (-0.0253 of beta bought 0.59 km). If these",
            "                two probes also do little, the pt length error is NOT a",
            "                beta problem - more likely the composition of who uses",
            "                pt, or the 8 km MiD reference itself. Do not chase it",
            "                with ever stronger betas: -0.09 is already a VoT of",
            "                25 EUR/h, and closing 5 km this way would need ~-0.25.",
            "",
            "car.alpha_u stays 0 (reference). car's beta is NOT probed: stage 1",
            "showed its length error is only +0.14 km, and the -0.1366 probe",
            "overshot to -0.45 - the effective -0.0397 from Table 2 plus the",
            "universal licence term is right, the old -0.0658 target does not carry",
            "over to this specification.",
            "",
            "CAVEAT on the B_* runs: at the stage-1 centre the mode composition was",
            "badly distorted (bicycle 35%), so those length readings sat on a skewed",
            "sample. Here they are measured at a centre that should be much closer",
            "on shares, so they are the first clean read on the betas.",
        ],
        "base": {"car.alpha_u": 0.0, **CENTRE},
        "extra_args": ["--use-vdf", "true"],
        "runs": runs,
    }

    OUT.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} with {len(runs)} runs\n")
    print(f"{'run':16} {'walk':>9} {'bike':>9} {'cp':>9} {'pt':>9}  extra")
    for r in runs:
        p = r["parameters"]
        extra = {k: v for k, v in p.items() if k not in STAGE1_CENTRE}
        print(f"{r['name']:16} {p['walk.alpha_u']:>9} {p['bike.alpha_u']:>9} "
              f"{p['bavariaCarPassenger.alpha_u']:>9} {p['pt.alpha_u']:>9}  "
              f"{extra if extra else ''}")


if __name__ == "__main__":
    main()
