"""Regenerate asc_grid_stage1.json - first round on the Table-2 specification.

This is a SCREENING round, not an optimisation. The utility function changed
completely (Table 2, interactions now active), so every ASC from the earlier
calibration series - which ran against the previous specification - is void and
we have no prior for the new ones.

With 16 parallel slots the efficient move is a centre-plus-axis design: it
measures d(share)/d(ASC) for every mode in ONE batch, including the cross
effects we have so far only assumed to be small. The optimal ASC vector can
then be computed in one shot instead of being searched over several rounds.

Lengths come for free: every run reports distance_mae, so the centre run alone
tells us how far the Table-2 betas are off. The B_* probes additionally test,
already in this round, whether the beta targets found by the earlier length
calibration still hold under the new specification.

Run: python gen_stage1_grid.py
"""
import json
from pathlib import Path

OUT = Path(__file__).with_name("asc_grid_stage1.json")

# Table 2 (perceived costs) as implemented in BavariaModeParameters.
CENTRE = {
    "car.alpha_u": 0.0,            # reference, never varied
    "walk.alpha_u": 0.8438,
    "bike.alpha_u": 0.4624,
    "bavariaCarPassenger.alpha_u": -2.0608,
    "pt.alpha_u": -0.1226,
}

# Axis step. The earlier PT sweep measured a response of ~8pp share per utility,
# so 0.4 u is worth ~3pp - clearly above run-to-run noise, while staying small
# enough that the response is still locally linear.
STEP = 0.4

SWEPT = ["walk.alpha_u", "bike.alpha_u", "bavariaCarPassenger.alpha_u", "pt.alpha_u"]

# Base travel-time betas, moved to what the earlier length calibration wanted.
# car: it is only available to licence holders, so the +0.0708 licence term applies
# to every car trip; to land at an effective -0.0658 the base must be -0.1366.
BETA_PROBES = {
    "car": {"car.betaTravelTime_u_min": -0.1366},
    "cp": {"bavariaCarPassenger.betaInVehicleTravelTime_u_min": -0.1000},
    "bike": {"bike.betaTravelTime_u_min": -0.1200},
    "pt": {"pt.betaInVehicleTime_u_min": -0.0379},
}


def build_runs():
    runs = [{"name": "C_centre", "parameters": {}}]

    for key in SWEPT:
        short = key.split(".")[0].replace("bavariaCarPassenger", "cp").replace("alpha_u", "")
        for sign in ("+", "-"):
            delta = STEP if sign == "+" else -STEP
            runs.append({
                "name": f"A_{short}{sign}{STEP}",
                "parameters": {key: round(CENTRE[key] + delta, 4)},
            })

    # Common-offset direction: all non-car ASCs together. Car is pinned at 0, so a
    # shift of every other mode is a genuine degree of freedom, not a re-normalisation.
    for sign in ("+", "-"):
        delta = STEP if sign == "+" else -STEP
        runs.append({
            "name": f"D_all{sign}{STEP}",
            "parameters": {k: round(CENTRE[k] + delta, 4) for k in SWEPT},
        })

    for label, params in BETA_PROBES.items():
        runs.append({"name": f"B_beta_{label}", "parameters": dict(params)})

    runs.append({
        "name": "B_beta_all",
        "parameters": {k: v for p in BETA_PROBES.values() for k, v in p.items()},
    })

    return runs


def main():
    runs = build_runs()

    spec = {
        "_comment": [
            f"Stage-1: first round on the Table-2 specification. {len(runs)} runs.",
            "GENERATED by gen_stage1_grid.py - regenerate, do not hand-edit.",
            "",
            "SCREENING round, not an optimisation. The utility function changed",
            "completely (Mueller/Engelhardt Table 2, socio-demographic terms now act",
            "as interactions on time), so the ASCs of the earlier calibration series",
            "- run against the previous specification - are void.",
            "",
            "C_centre  - Table 2 exactly as estimated. Its share errors are the",
            "            starting point, its distance errors tell us how far the",
            "            Table-2 betas are off, for all five modes at once.",
            "A_*       - one ASC at a time, +-0.4 u. These give d(share)/d(ASC) per",
            "            mode INCLUDING the cross effects. Feed them into",
            "            alpha += ln(target/sim) with the MEASURED gradient instead",
            "            of the theoretical one - the earlier sweep showed the plain",
            "            formula underestimates by roughly a factor of 2 here.",
            "D_*       - all four non-car ASCs shifted together. Car is pinned at 0,",
            "            so this is a real degree of freedom (it changes every mode",
            "            relative to car), and it is the direction a wrong overall",
            "            level would show up in.",
            "B_beta_*  - do the earlier beta findings still hold under the new",
            "            specification? car -0.1366 (base, so that the universal",
            "            +0.0708 licence term lands on an effective -0.0658),",
            "            car_passenger -0.1000, bike -0.1200, pt -0.0379.",
            "            Judge these by distance_mae, not share_mae.",
            "",
            "car.alpha_u stays 0 everywhere: it is the reference alternative.",
            "DRT is not in the base-case choice set, so its parameters are left at",
            "the values from BavariaModeParameters and are not varied here.",
            "",
            "Expect the Table-2 betas to produce trips that are TOO LONG: car is",
            "effectively -0.0397 where the earlier calibration wanted -0.0658,",
            "car_passenger -0.0638 where it wanted -0.1000, and pt -0.0126 where it",
            "was already too long at -0.0379. Those targets come from the previous",
            "specification, which is exactly why the B_* probes re-test them here.",
        ],
        "base": dict(CENTRE),
        "extra_args": ["--use-vdf", "true"],
        "runs": runs,
    }

    OUT.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} with {len(runs)} runs\n")
    for i, r in enumerate(runs):
        print(f"{i:3d}  {r['name']:18} {r['parameters'] if r['parameters'] else '(Table 2 as estimated)'}")


if __name__ == "__main__":
    main()
