"""Regenerate asc_grid_stage3.json - third round on the Table-2 specification.

Stage 2 took share_mae from 8.13 to 1.84 pp and dist_mae from 3.33 to 1.54 km:
the large extrapolation out of stage 1 held. What is left are two length errors
that the beta probes - measured for the first time at an undistorted centre -
showed how to fix:

    car_passenger  +3.18 km  ->  beta -0.13 lands it at +0.08 km (costs 5 pp share)
    pt             +2.51 km  ->  beta -0.06 lands it at +1.37 km (costs 5.4 pp)
                                 beta -0.09 lands it at +0.33 km (costs 8.0 pp)

This round adopts those betas and hands the share they cost back to the ASCs,
solved through the gradient measured locally at the stage-2 centre.

Two approximations are baked into that centre and are the main thing being
tested here: the share effects of the cp and pt betas are assumed ADDITIVE, and
the ASC solve is linear. The F_* fallbacks exist so that a failure of either is
recoverable without losing the round.

Run: python gen_stage3_grid.py
"""
import json
from pathlib import Path

import numpy as np

OUT = Path(__file__).with_name("asc_grid_stage3.json")

MODES = ["walk", "bicycle", "car_passenger", "car", "pt"]
SWEPT = ["walk.alpha_u", "bike.alpha_u", "bavariaCarPassenger.alpha_u", "pt.alpha_u"]

# Stage-2 centre and its measured mvv shares (%).
S2_CENTRE = {
    "walk.alpha_u": -0.1285,
    "bike.alpha_u": -0.9819,
    "bavariaCarPassenger.alpha_u": -2.0444,
    "pt.alpha_u": 0.1155,
}
S2_SHARES = np.array([19.82, 17.34, 12.37, 32.11, 18.36])
TARGET = np.array([21.0, 15.0, 12.0, 34.0, 18.0])

# d(share)/d(alpha) in pp per utility, measured at the stage-2 centre.
J = np.array([
    [9.69, -6.05, -1.05, -0.37],
    [-6.26, 12.96, -1.95, -3.06],
    [-0.80, -1.93, 7.78, -0.90],
    [-2.32, -2.02, -3.72, -1.89],
    [-0.31, -2.95, -1.06, 6.21],
])

# Share effect of each beta change, measured vs the stage-2 centre (pp, mvv).
CP_EFFECT = {-0.13: np.array([0.14, 1.04, -5.06, 2.72, 1.17])}
PT_BASE_BETA = -0.0126
PT_EFFECT = {
    -0.06: np.array([-0.05, 2.96, 1.08, 1.40, -5.39]),
    -0.09: np.array([-0.08, 4.97, 1.38, 1.76, -8.03]),
}


def pt_effect(beta):
    """Interpolate the pt share effect between the two measured probes."""
    if beta in PT_EFFECT:
        return PT_EFFECT[beta]
    d1, d2 = -0.06 - PT_BASE_BETA, -0.09 - PT_BASE_BETA
    e1, e2 = PT_EFFECT[-0.06], PT_EFFECT[-0.09]
    d = beta - PT_BASE_BETA
    return e1 + (e2 - e1) * (d - d1) / (d2 - d1)


def solve_ascs(effect):
    """ASCs that restore the target shares after a beta change shifted them."""
    predicted = S2_SHARES + effect
    delta, *_ = np.linalg.lstsq(J, TARGET - predicted, rcond=None)
    return {k: round(S2_CENTRE[k] + d, 4) for k, d in zip(SWEPT, delta)}, delta


def point(cp_beta=None, pt_beta=None):
    effect = np.zeros(len(MODES))
    betas = {}
    if cp_beta is not None:
        effect = effect + CP_EFFECT[cp_beta]
        betas["bavariaCarPassenger.betaInVehicleTravelTime_u_min"] = cp_beta
    if pt_beta is not None:
        effect = effect + pt_effect(pt_beta)
        betas["pt.betaInVehicleTime_u_min"] = round(pt_beta, 4)
    ascs, delta = solve_ascs(effect)
    return {**ascs, **betas}, delta


CENTRE, CENTRE_DELTA = point(cp_beta=-0.13, pt_beta=-0.06)
STEP = 0.25
SCALES = [0.6, 1.4]


def build_runs():
    runs = [{"name": "C_centre", "parameters": dict(CENTRE)}]

    for key in SWEPT:
        short = {"walk.alpha_u": "walk", "bike.alpha_u": "bike",
                 "bavariaCarPassenger.alpha_u": "cp", "pt.alpha_u": "pt"}[key]
        for sign in ("+", "-"):
            p = dict(CENTRE)
            p[key] = round(CENTRE[key] + (STEP if sign == "+" else -STEP), 4)
            runs.append({"name": f"A_{short}{sign}{STEP}", "parameters": p})

    # Scale the ASC step taken from the stage-2 centre, betas unchanged.
    for s in SCALES:
        p = dict(CENTRE)
        for key, d in zip(SWEPT, CENTRE_DELTA):
            p[key] = round(S2_CENTRE[key] + s * d, 4)
        runs.append({"name": f"S_scale{s}", "parameters": p})

    for b in [-0.045, -0.075, -0.09]:
        p, _ = point(cp_beta=-0.13, pt_beta=b)
        runs.append({"name": f"B_pt{b}", "parameters": p})

    # Fallbacks: drop one assumption at a time.
    p, _ = point(cp_beta=-0.13)
    runs.append({"name": "F_cp_only", "parameters": p})

    p, _ = point()
    runs.append({"name": "F_asc_only", "parameters": p})

    return runs


def main():
    runs = build_runs()

    spec = {
        "_comment": [
            f"Stage-3 on the Table-2 specification. {len(runs)} runs.",
            "GENERATED by gen_stage3_grid.py - regenerate, do not hand-edit.",
            "",
            "Stage 2: share_mae 8.13 -> 1.84 pp, dist_mae 3.33 -> 1.54 km. The large",
            "extrapolation out of stage 1 held, and the beta probes read cleanly for",
            "the first time (stage 1 measured them at 35% bicycle share).",
            "",
            "This round adopts the two length-fixing betas and hands back the share",
            "they cost, via the gradient measured locally at the stage-2 centre:",
            "  car_passenger -0.13  ->  length +3.18 km becomes +0.08 km, costs 5.1 pp",
            "  pt            -0.06  ->  length +2.51 km becomes +1.37 km, costs 5.4 pp",
            "",
            "C_centre   both betas, ASCs solved to restore all five shares.",
            "A_*        axes at +-0.25 - the gradient has to be re-measured again,",
            "           it already flattened noticeably between stage 1 and 2",
            "           (bicycle's own effect 19.6 -> 13.0 pp/u).",
            "S_*        the ASC step from the stage-2 centre at 0.6x and 1.4x. The",
            "           stage-2 ray showed the optimum sat slightly past 1.0x, so",
            "           this brackets the same kind of mild non-linearity.",
            "B_pt*      pt beta ladder at -0.045 / -0.075 / -0.09, each with its own",
            "           re-solved ASCs. -0.09 closes the length almost completely",
            "           (+0.33 km) but costs 8 pp of share and needs a pt ASC above",
            "           +1.0; -0.045 is the cautious end.",
            "",
            "TWO ASSUMPTIONS are being tested by the centre itself: that the cp and",
            "pt beta share-effects ADD, and that the ASC solve is linear over this",
            "step. The fallbacks drop one each, so the round survives either failing:",
            "  F_cp_only   cp beta only, no pt beta, ASCs solved for that alone",
            "  F_asc_only  no beta change at all, pure ASC update on stage 2",
            "",
            "NOT pursued, deliberately:",
            "  car length is -1.88 km here but was +0.14 km at the stage-1 centre, so",
            "  it is strongly composition-dependent. car's effective beta is already",
            "  -0.0397 (10.9 EUR/h); weakening it further to buy 1.9 km would be the",
            "  wrong instrument - that points at destination structure, not at time",
            "  sensitivity.",
            "  pt length is zonally split (mvv +2.51, munich +3.79, umland +1.00). A",
            "  global beta cannot hit both; -0.06 rather than -0.09 keeps the umland",
            "  from overshooting.",
        ],
        "base": {"car.alpha_u": 0.0, **{k: CENTRE[k] for k in SWEPT}},
        "extra_args": ["--use-vdf", "true"],
        "runs": runs,
    }

    OUT.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} with {len(runs)} runs\n")
    hdr = f"{'run':16} {'walk':>9} {'bike':>9} {'cp':>9} {'pt':>9}  betas"
    print(hdr)
    for r in runs:
        p = r["parameters"]
        betas = {k.split(".")[-1].replace("betaInVehicleTravelTime_u_min", "cp_b")
                 .replace("betaInVehicleTime_u_min", "pt_b"): v
                 for k, v in p.items() if "beta" in k}
        print(f"{r['name']:16} {p['walk.alpha_u']:>9} {p['bike.alpha_u']:>9} "
              f"{p['bavariaCarPassenger.alpha_u']:>9} {p['pt.alpha_u']:>9}  {betas}")


if __name__ == "__main__":
    main()
